server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: iflot-access-modernization-api

  datasource:
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:iflot_access}
      username: ${DB_USERNAME:iflot}
      password: ${DB_PASSWORD:iflot123}
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never